# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/dist_mem_gen_D_1/dist_mem_gen_D.xci
# IP: The module: 'dist_mem_gen_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/dist_mem_gen_D_1/dist_mem_gen_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_D'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/dist_mem_gen_D_1/dist_mem_gen_D.xci
# IP: The module: 'dist_mem_gen_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/dist_mem_gen_D_1/dist_mem_gen_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
