# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/blk_mem_gen_D/blk_mem_gen_D.xci
# IP: The module: 'blk_mem_gen_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/blk_mem_gen_D/blk_mem_gen_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_D'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/blk_mem_gen_D/blk_mem_gen_D.xci
# IP: The module: 'blk_mem_gen_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/blk_mem_gen_D/blk_mem_gen_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
