# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w.xci
# IP: The module: 'crc_blk_mem_1w_8w' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'crc_blk_mem_1w_8w'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w.xci
# IP: The module: 'crc_blk_mem_1w_8w' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'crc_blk_mem_1w_8w'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
