# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125.xci
# IP: The module: 'clk_wiz_250_125' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_250_125'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_250_125'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_250_125'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125.xci
# IP: The module: 'clk_wiz_250_125' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_250_125'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_250_125'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/projects/vivado/turboDec/turboDec.srcs/sources_1/ip/clk_wiz_250_125/clk_wiz_250_125_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_250_125'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
