# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1157-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.cache/wt [current_project]
set_property parent.project_path C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w.xci
set_property used_in_implementation false [get_files -all c:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w.dcp]
set_property is_locked true [get_files C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top crc_blk_mem_1w_8w -part xc7vx690tffg1157-2 -mode out_of_context
rename_ref -prefix_all crc_blk_mem_1w_8w_
write_checkpoint -noxdef crc_blk_mem_1w_8w.dcp
catch { report_utilization -file crc_blk_mem_1w_8w_utilization_synth.rpt -pb crc_blk_mem_1w_8w_utilization_synth.pb }
if { [catch {
  file copy -force C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.runs/crc_blk_mem_1w_8w_synth_1/crc_blk_mem_1w_8w.dcp C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim C:/Graduate/PCIe/Turbo/pcie_turbo_debug/pcie_turbo.srcs/sources_1/ip/crc_blk_mem_1w_8w/crc_blk_mem_1w_8w_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
